import type { InspirationPrompt } from './inspirationPrompts'

// 模板和示例图固定上游版本；示例图保留原作者来源，不能视为模板的生成结果。
export const INSPIRATION_TEMPLATES: InspirationPrompt[] = [
  {
    id: 'canghe-template-ui-screenshot-system',
    previewImage: 'inspiration/case336.webp',
    previewSourceLabel: '苍何原创实测',
    previewSourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-336',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-336',
    title: 'UI 截图系统',
    category: 'UI 与界面',
    sourceCategory: 'UI & Interfaces',
    description: '生成 App、网页、仪表盘、社媒截图等高保真界面。',
    prompt: '为[产品类型]生成一张[平台，如 iOS/Android/Web]界面图。\n核心功能：[功能点A]、[功能点B]、[功能点C]。\n视觉风格：[极简/科技/拟物]，主色[颜色]，强调色[颜色]。\n布局：[顶部导航/双栏/卡片流]，信息层级清晰，留白充足。\n输出：高保真UI截图，文字清晰可读，比例[9:16/16:9]。',
    tags: ['界面', '仪表盘', '截图', '科技', '社媒'],
    guidance: ['锁定平台、比例、层级和画面文字。', '明确状态栏、Tab、操作区、评论层等 UI 元素。'],
    pitfalls: ['避免平台描述过泛。', '约束文字可读性和平台特征。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-ui',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-infographic-engine',
    previewImage: 'inspiration/case334.webp',
    previewSourceLabel: '苍何原创实测（公众号文章《我逆向了 329 条 GPT-Image2 提示词模板，全部开源！》）',
    previewSourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-334',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-334',
    title: '信息图引擎',
    category: '图表与信息可视化',
    sourceCategory: 'Charts & Infographics',
    description: '生成结构化图解、时间线、知识图谱和技术解释图。',
    prompt: '生成[主题：明确、具体，避免宽泛。例如：“老年人日常健康管理指南”而非“健康”]信息图，目标读者为[人群:细化人群特征，如年龄段、职业、兴趣等]。\n结构：标题区 + [3-5]个模块（每模块含图标、短标题、1-2句说明,模块间逻辑：可用箭头、颜色区分或连接线提示信息流或关系等适当的方式）。\n图表类型：[流程图/对比图/关系图/时间线]。\n风格：[专业报告/科普插画/儿童教育等]，主色[颜色]，背景[浅色/深色]。\n输出：信息层级清晰、可读性高的中文信息图。',
    tags: ['信息图', '图表', '教育', '科技'],
    guidance: ['定义 3-5 个模块、信息流、层级和短标签。', '用色块、箭头、图标和留白控制复杂度。'],
    pitfalls: ['避免把长段正文塞进画面。', '先限制模块数量，再补视觉细节。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-infographic',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-scientific-scale-diagram',
    previewImage: 'inspiration/case380.webp',
    previewSourceLabel: '@Gdgtify',
    previewSourceUrl: 'https://x.com/Gdgtify/status/2051288232613351571',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-380',
    title: '科学尺度缩放图',
    category: '图表与信息可视化',
    sourceCategory: 'Charts & Infographics',
    description: '生成多尺度科学信息图，强调层级、标签和可读性。',
    prompt: '为[主题]生成一张科学尺度缩放信息图。\n结构：6-8 个圆形或六边形框，按从微观到宏观的尺度递进排列。\n每个框包含：尺度名称、3-5 个词的洞察、测量单位或放大倍率，以及该尺度下的高细节 3D 渲染。\n用细线连接各尺度，避免重复层级。标题使用“[主题]：AT EVERY SCALE”或“ZOOM: THE WORLD OF [主题]”。\n风格：科学编辑信息图、精准微距光、清晰层级、文字短而可读。\n约束：不要通用放大镜图标，不要把所有尺度画成同一大小，不要塞长段正文。',
    tags: ['信息图', '图表', '教育', '写实', '科技'],
    guidance: ['使用 6-8 个尺度框，每个标签保持短句。', '展示单位、倍率和不同尺度的细节。'],
    pitfalls: ['避免所有尺度框长得一样。', '避免通用放大镜式布局。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-infographic',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-poster-layout-system',
    previewImage: 'inspiration/case345.webp',
    previewSourceLabel: '@bananaprompts',
    previewSourceUrl: 'https://x.com/bananaprompts/status/2048541390900994476',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-345',
    title: '海报排版系统',
    category: '海报与排版',
    sourceCategory: 'Posters & Typography',
    description: '生成活动、产品、电影和社媒传播海报。',
    prompt: '设计一张[活动/产品/电影]海报，主题为[主题词]。\n主视觉：[主体元素]，标题文案：[标题]，副标题：[副标题]。\n版式：[居中/左对齐/对角构图]，风格：[复古/未来/极简]。\n色彩：[主色 + 辅色]，氛围：[情绪关键词]。\n输出：可用于社媒传播的高分辨率海报。',
    tags: ['海报', '字体', '商业 Campaign', '商业', '社媒'],
    guidance: ['锁定主体、标题、版式、配色和比例。', '突出标题层级和主视觉。'],
    pitfalls: ['需要成品海报时，避免生成拼贴展示板。', '约束多余文字和装饰符号。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-poster',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-sports-campaign-poster',
    previewImage: 'inspiration/case350.webp',
    previewSourceLabel: '@ryanpp27',
    previewSourceUrl: 'https://x.com/ryanpp27/status/2048602248524214542',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-350',
    title: '运动商业 Campaign',
    category: '海报与排版',
    sourceCategory: 'Posters & Typography',
    description: '生成运动员、道具、品牌色统一的商业运动海报。',
    prompt: '设计一张[运动项目/健身品类]商业 Campaign 海报。\n主体：[运动员/模特/产品道具]，姿态：[坐姿/冲刺/挥拍/力量动作]。\n核心道具：[球拍/哑铃/球鞋/球衣]，以夸张比例或对角构图成为视觉锚点。\n版式：[单张强主视觉/三联画/数据涂鸦海报]。\n大字标题："[主标题]"，辅助文案："[短句/数据/精神口号]"。\n视觉风格：高端运动品牌广告，强光影，反光地面，干净构图，品牌化配色[主色+辅助色]。\n约束：主体清晰，文字可读，色调统一，不要杂乱拼贴，不要生成错误运动器材。\n输出：1:1 或 4:5，适合社媒传播的运动商业视觉。',
    tags: ['海报', '商业 Campaign', '字体', '写实', '商业', '时尚'],
    guidance: ['定义运动项目、姿态、核心道具、标题和品牌色。', '使用强光影、干净构图和可读数据层。'],
    pitfalls: ['避免错误运动器材和杂乱拼贴。', '让运动员和核心道具占据主导。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-poster',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-conceptual-typography-poster',
    previewImage: 'inspiration/case355.webp',
    previewSourceLabel: '@dotey',
    previewSourceUrl: 'https://x.com/dotey/status/2048793351290327381',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-355',
    title: '概念字体海报',
    category: '海报与排版',
    sourceCategory: 'Posters & Typography',
    description: '生成以标题文字为主视觉的高级字体海报。',
    prompt: 'Create ONE finished premium conceptual typography poster for the exact title:\n\n"[标题/词语/短句]"\n\nSingle poster only. No moodboard, grid, presentation board, mockup, captions, prompt text, process sheet, or sample labels.\n\nThe title must be the dominant visual structure of the poster: huge, readable, powerful, and spelled exactly. Do not translate, shorten, replace, or misspell it. Do not add other large readable text.\n\nSilently interpret the title\'s meaning, mood, cultural aura, symbolic associations, psychological tension, and visual rhythm. Turn that interpretation into one strong visual metaphor.\n\nTypography is the hero. Design custom-looking letterforms whose weight, width, contrast, spacing, rhythm, distortion, negative space, edge quality, and ink texture express the temperament of the title. The type should feel intentionally designed, not like a default font.\n\nIf the title refers to a widely known person, make a large editorial portrait or half-body figure a major visual presence, occupying roughly 40%-70% of the composition. The figure should interact with the typography: overlapping the letters, emerging from them, being framed by them, casting shadows on them, breaking through them, or being partially hidden behind them.\n\nFor abstract or non-person titles, use a human figure, landscape, object, or atmospheric setting only when it strengthens the meaning. It must interact with the typography and deepen the concept, not decorate it.\n\nUse a restrained 4-6 color system matched to the theme: dominant background color, primary typography color, figure / landscape tone, emotional accent color, muted support color, and subtle paper / ink texture tone.\n\nComposition style: high-end editorial poster, museum-quality graphic design, dramatic scale, strong hierarchy, few elements, intelligent whitespace, bold flat color areas, sharp cropping, silkscreen / lithograph / risograph grain, paper fibers, subtle ink imperfections, refined visual tension.\n\nAvoid generic word art, glossy 3D lettering, random icons, stock-photo realism, cluttered collage, excessive grunge, tourist clichés, official logos, copied slogans, copied campaign aesthetics, unrelated text, and misspelled typography.',
    tags: ['字体', '海报', '风格', '创意', '社媒'],
    guidance: ['让字体成为画面主角，并保证标题拼写准确。', '人物、物体或风景需要服务标题含义。'],
    pitfalls: ['避免默认字效、无关图标和标题错字。', '控制配色数量，保持克制。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-poster',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-ink-double-exposure-poster',
    previewImage: 'inspiration/case359.webp',
    previewSourceLabel: '@Goodmanprotocol',
    previewSourceUrl: 'https://x.com/Goodmanprotocol/status/2049002279051895243',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-359',
    title: '水墨双重曝光海报',
    category: '海报与排版',
    sourceCategory: 'Posters & Typography',
    description: '生成水墨、人像与层叠氛围结合的视觉海报。',
    prompt: '生成一张[人物/角色/品牌主理人/运动员]的水墨双重曝光人物海报。\n画幅：9:16 竖版，高级电影海报构图。\n主体结构：\n- 上半区：放大的人物头部、面部轮廓或半身剪影，形成最强识别锚点。\n- 中下区：同一人物的全身或半身主体，姿态为[站姿/动作姿态/凝视镜头]。\n- 剪影内部：融合[关键场景]、[象征物]、[叙事片段]、[环境纹理]，形成双重曝光叙事。\n视觉连接：用云雾、水墨扩散、飞白边缘、负空间和柔和明暗过渡，把上方剪影、内部拼贴和下方主体连成一条从上到下的视觉动线。\n风格：东方水墨美学 + 写实电影感，克制、高级、留白充足，层次丰富但不杂乱。\n文字：可加入[标题/姓名/短句]，必须少量、可读、像海报题签而不是信息图说明。\n约束：不要硬拼贴，不要把背景塞满，不要廉价武侠特效，不要复制真实海报版式，不要让剪影和主体互相抢焦点。\n输出：海报级完成图，主体清晰，水墨边缘自然，叙事元素与人物身份强相关。',
    tags: ['海报', '古典', '风格', '插画', '叙事', '历史'],
    guidance: ['融合人像剪影、水墨质感、氛围和留白。', '保持构图克制、高级、可读。'],
    pitfalls: ['避免廉价奇幻拼贴和景物堆叠。', '非必要时减少文字。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-poster',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-nature-science-poster',
    previewImage: 'inspiration/case339.webp',
    previewSourceLabel: '@berryxia',
    previewSourceUrl: 'https://x.com/berryxia/status/2048251413147644100',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-339',
    title: '自然科普海报',
    category: '海报与排版',
    sourceCategory: 'Posters & Typography',
    description: '生成极简产品感自然科普海报。',
    prompt: '你是一个高端自然科普海报生成系统，目标是为稀有动物、昆虫、爬行动物、哺乳动物或其他小众生物生成 Apple keynote 风格的高级科普视觉海报。\n\n整体视觉方向：\n生成一张 9:16 竖版高级科普海报，画面采用极简、纯白、干净、现代、Apple 式产品发布海报语言。背景应为纯白或极浅灰白渐变，保持大量留白。整体设计应具备高级感、克制感、视觉冲击力和科学展示感。\n\n核心设计原则：\n1. 主体动物必须被极度放大，成为画面最强视觉中心。\n2. 主体应具有强烈立体感、真实质感、高清细节和柔和棚拍光影。\n3. 海报信息要少而准，避免拥挤。\n4. 不使用传统信息图的卡片、圆角框、复杂底纹、淡黄色纸张质感或装饰性边框。\n5. 底部信息区只使用四列极简 icon + 标题 + 短说明，通过细竖线分隔。\n6. 文字排版要像高端发布会视觉，标题巨大，副标题克制，正文小而清晰。\n7. 风格关键词：Apple-inspired, premium editorial, pure white background, hero subject, clean typography, minimal infographic, high-end science poster.\n\n画面结构：\n顶部左侧为标题区：\n中文大标题：{中文物种名}\n中文副标题：{一句有吸引力的物种定位}\n细短横线\n英文名：{英文物种名}\n分布信息：主要分布：{分布区域}\n\n中部与下中部为主体视觉：\n生成一个超高清、真实、具有强烈立体感的 {中文物种名}。\n主体应占据画面 50% 到 70% 的视觉面积。\n主体姿态应具有展示性、力量感或识别度。\n保持白色背景，不添加复杂自然环境。\n可以保留少量必要承托物，例如树枝、岩石、雪地、沙土或木皮，但必须简洁。\n主体要有真实阴影，使其像高级产品摄影一样立在画面中。\n\n底部信息区：\n用四个极简信息栏目展示科普信息。\n每个栏目包含：\n一个细线 icon\n一个彩色小标题\n一段 1 到 3 行短文字\n栏目之间用极细浅灰竖线分隔。\n不使用卡片框，不使用圆角背景，不使用大面积色块。\n\n四个信息栏目：\n栏目 1：\n标题：{重点特征1标题}\n说明：{重点特征1短说明}\n\n栏目 2：\n标题：{重点特征2标题}\n说明：{重点特征2短说明}\n\n栏目 3：\n标题：{重点特征3标题}\n说明：{重点特征3短说明}\n\n栏目 4：\n标题：{重点特征4标题}\n说明：{重点特征4短说明}\n\n底部总结句：\n在最底部居中放置一句灰色小字总结：\n{一句高级、克制、有记忆点的科普总结}\n\n字体与排版：\n中文标题使用大号黑色、高级、稳重、有力量感的字体。\n副标题使用灰色，中等字号，字距略宽。\n英文名使用小号灰色，简洁现代。\n正文使用清晰现代中文字体，保持可读。\n所有文字必须留有足够呼吸感。\n\n色彩规范：\n背景：纯白、极浅灰、轻微柔光渐变。\n主标题：黑色或深石墨色。\n副标题与正文：中性灰。\n底部四个信息标题可使用低饱和强调色：\n暖棕、冷蓝、松石绿、紫色、橙色。\n颜色只用于 icon 和小标题，不要大面积铺色。\n\n图像质量：\n2K 高清质感，细节清晰，主体锐利，光影真实。\n主体纹理必须可信，例如毛发、鳞片、甲壳、皮肤褶皱、羽毛或斑纹。\n避免变形、错误肢体、错误解剖结构、模糊主体、低质贴图、塑料感、卡通感。\n\n禁止项：\n不要使用淡黄色旧纸背景。\n不要使用复杂信息图网格。\n不要使用圆角卡片。\n不要使用厚边框。\n不要使用大面积装饰图形。\n不要添加无关 logo。\n不要添加多余小字。\n不要让主体太小。\n不要让文字压住主体。\n不要让底部信息区过度拥挤。\n不要出现儿童科普风、卡通风、低端展板风。\n\n最终输出：\n生成一张 9:16 竖版、高级、干净、强视觉冲击的 Apple 风自然科普海报。',
    tags: ['海报', '教育', '风格', '信息图'],
    guidance: ['使用清晰主体、少量文案、柔和阴影和充足留白。', '让科普标签短而清楚。'],
    pitfalls: ['避免广告感太重。', '避免密集百科正文。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-poster',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-product-commerce-visual',
    previewImage: 'inspiration/case373.webp',
    previewSourceLabel: '@xpg0970',
    previewSourceUrl: 'https://x.com/xpg0970/status/2050108279385419965',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-373',
    title: '商品商业视觉',
    category: '商品与电商',
    sourceCategory: 'Products & E-commerce',
    description: '生成商品图、包装、详情页和卖点排版。',
    prompt: '生成[商品名]电商主图，卖点为[卖点1]、[卖点2]。\n场景：[纯色棚拍/生活方式场景]，镜头：[特写/半身/全景]。\n材质细节：[材质关键词]，灯光：[柔光/侧光/轮廓光]。\n附加元素：[价格角标/卖点icon/促销文案]。\n输出：电商平台可直接使用的商品展示图。',
    tags: ['商品', '商业', '包装', '写实', '食品饮品'],
    guidance: ['定义商品、卖点、材质、场景、光线和版块。', '区分主商品、卖点标签和辅助道具。'],
    pitfalls: ['避免无关道具削弱商品识别。', '约束包装文字和卖点表达。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-product',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-personalized-beauty-report',
    previewImage: 'inspiration/case353.webp',
    previewSourceLabel: '@liyue_ai',
    previewSourceUrl: 'https://x.com/liyue_ai/status/2048667226195317219',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-353',
    title: '个性化美妆报告',
    category: '商品与电商',
    sourceCategory: 'Products & E-commerce',
    description: '生成美妆与生活方式产品的推荐报告版式。',
    prompt: '你是一个专业美妆顾问 + 人脸分析系统 + 品牌视觉设计系统。\n目标：基于[用户自拍]与[口红品牌]，生成一张具有“分析 + 推荐 + 试色 + 场景建议”的竖版口红推荐报告信息图。\n\n输入参数：\n用户图像：[用户自拍]\n品牌：[Dior / YSL / Armani / Chanel / TF / 其他品牌]\n风格偏好（可选）：[通勤 / 温柔 / 气场 / 氛围感 / 显白优先]\n推荐数量：[3-5]\n\n分析层：\n- 判断肤色：冷 / 暖 / 中性（含明度）\n- 判断气质：清冷 / 温柔 / 明艳 / 干净 / 成熟\n- 判断唇部基础：唇色深浅、唇形、适合浓淡\n- 输出一句总结：「更适合 [色系] + [饱和度] + [质地] 的口红方向」\n\n推荐层：\n从[品牌]中筛选[3-5]个差异化色号，每个色号包含：\n- 色号名称\n- 色系标签\n- 上脸效果\n- 推荐场景\n\n品牌视觉层：\n根据[品牌]自动生成视觉调性，只用少量品牌强调色做标题、细线、小 icon 和局部点缀。\n示例：YSL 黑金强对比，Dior 法式柔光灰白，Armani 低饱和雾面，Chanel 极简黑白，TF 深色电影感。\n\n版式结构：\n左上：用户输入图 + 肤色分析\n右上：一句分析结论\n中部：3-5 个同一张脸的唇色试色矩阵，每列一个色号\n底部：有判断力的个人建议\n\n视觉要求：\n高端美妆编辑视觉，结构化信息可视化排版，真实皮肤质感，唇色精准，统一光影，9:16 竖版，8K。',
    tags: ['商品', '版式', '风格', '界面', '商业', '时尚'],
    guidance: ['使用诊断、推荐和商品卡片的报告层级。', '对齐商品图、标签和评分。'],
    pitfalls: ['避免医疗化结论和难读小字。', '保持推荐逻辑清楚。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-product',
    referenceCount: 1,
  },
  {
    id: 'canghe-template-brand-identity-package',
    previewImage: 'inspiration/case354.webp',
    previewSourceLabel: '@wanerfu',
    previewSourceUrl: 'https://x.com/wanerfu/status/2048659924822184026',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-354',
    title: '品牌身份包',
    category: '品牌与标志',
    sourceCategory: 'Brand & Logos',
    description: '生成 Logo、配色、字体、应用触点与品牌系统。',
    prompt: '你是顶级品牌代理创意总监，目标是为[业务/产品]交付一套覆盖 Logo、配色、字体、语调和应用触点的完整品牌身份系统。\n\n输入信息：\n业务名称：[业务名]\n业务描述：[一句话说明]\n行业：[行业]\n目标受众：[详细描述]\n竞争对手：[3-5个]\n品牌个性：[5个关键词]\n希望触发的感受：[信任 / 兴奋 / 奢华 / 亲近 / 力量 / 其他]\n喜欢的视觉身份：[3个参考]\n讨厌的视觉身份：[3个反例]\n设计预算：[免费 / 付费]\n\n请输出：\n1. 品牌战略基础：品牌原型、核心承诺、定位、差异化和唯一关键词。\n2. Logo 概念：生成 3-5 个完全不同的 Logo 方向，每个方向说明核心视觉理念、形状语言、象征意义、字体方向、第一眼情绪和适用触点。\n3. 配色系统：主色、辅助色、强调色、中性色、HEX 代码、心理学解释、使用规则和禁用搭配。\n4. 字体系统：标题字体、正文字体、强调字体、字号层级、字距、行高和免费替代方案。\n5. 应用触点：名片、App 图标、网站首页、社媒模板、广告牌或包装上的应用效果。\n6. 品牌规则：3 条永远不要打破的核心品牌规则。\n\n输出形式：\n结构化品牌手册，任何设计师、开发者或 AI 工具都能在 10 分钟内理解并复用。',
    tags: ['品牌', 'Logo', '身份系统', '商业'],
    guidance: ['定义品牌名、定位、配色、字体、Logo 用法和触点。', '要求视觉板中的应用统一对齐。'],
    pitfalls: ['避免无关 Logo 变体和混乱配色。', '保持品牌文字准确。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-brand',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-brand-touchpoint-board',
    previewImage: 'inspiration/case362.webp',
    previewSourceLabel: '@Preda2005',
    previewSourceUrl: 'https://x.com/Preda2005/status/2049846981271699685',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-362',
    title: '品牌触点视觉板',
    category: '品牌与标志',
    sourceCategory: 'Brand & Logos',
    description: '生成包装、社媒、网页和展示场景里的品牌触点板。',
    prompt: '为[品牌名]生成一张高端品牌触点系统视觉板，不是单张海报，而是一套完整品牌应用展示。\n\n品牌定位：[行业/生活方式/产品品类]\n核心气质：[关键词1]、[关键词2]、[关键词3]\n主视觉场景：[核心产品/服务/体验]，放在[材质表面/空间场景]中，使用[光线]和[镜头]呈现。\n\n触点系统必须包含：\n- 主产品 hero shot\n- 包装盒 / 手提袋 / 杯子 / 标签 / 贴纸 / 封签等品牌物料\n- 菜单卡 / 价目表 / 小型排版样张\n- 生活方式场景或用户使用片段\n- 配色、字体、图形语言在不同触点上的统一应用\n\n设计语言：\n[现代极简/日式留白/奢华编辑/科技品牌]，主色[颜色]，辅助色[颜色]，大量留白，细腻材质，真实阴影，微小文字清晰可读。\n\n构图要求：\n像顶级设计机构提案页，所有触点整齐但不死板，主视觉最突出，辅助物料层级清楚，整体有品牌系统感和可落地感。\n\n约束：\n不要只生成一个 logo；不要把所有物料挤成杂乱拼贴；不要使用随机乱码文字；不要让包装、菜单、贴纸彼此风格割裂。',
    tags: ['品牌', '身份系统', '商业 Campaign', '商品', '商业', '社媒'],
    guidance: ['指定触点清单、统一视觉规则和样机排列。', '让所有面板共享配色和字体逻辑。'],
    pitfalls: ['避免混入多个无关 Campaign 风格。', '可读性下降时减少触点数量。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-brand',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-architecture-space',
    previewImage: 'inspiration/case331.webp',
    previewSourceLabel: '苍何原创实测（公众号文章《我逆向了 329 条 GPT-Image2 提示词模板，全部开源！》）',
    previewSourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-331',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-331',
    title: '建筑与空间',
    category: '建筑与空间',
    sourceCategory: 'Architecture & Spaces',
    description: '生成室内、建筑、城市地图和空间概念视觉。',
    prompt: '生成[空间类型]设计效果图，功能定位为[用途]。\n风格：[现代简约/工业/新中式]，材质：[木/石/金属/玻璃]。\n空间结构：[开敞/分区]，动线：[主通道说明]。\n光线：[自然采光/人工照明方案]，时间：[白天/夜景]。\n输出：写实建筑空间渲染图。',
    tags: ['建筑', '室内', '地图', '旅行', '商业'],
    guidance: ['定义视角、尺度、材质、光线和空间功能。', '地图需要指定地标、标签、边框装饰和准确度。'],
    pitfalls: ['概念图之外要避免不合理透视。', '锁定地图标签语言和相对位置。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-architecture',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-realistic-photography',
    previewImage: 'inspiration/case377.webp',
    previewSourceLabel: '@xRahultripathi',
    previewSourceUrl: 'https://x.com/xRahultripathi/status/2050677614168391716',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-377',
    title: '写实摄影',
    category: '摄影与写实',
    sourceCategory: 'Photography & Realism',
    description: '控制镜头、光线、胶片质感和纪实摄影效果。',
    prompt: '拍摄主题：[人物/物品/街景]，场景为[地点]。\n摄影参数风格：[35mm/85mm]，[浅景深/深景深]，[纪实/电影感]。\n光线：[自然光/夜景霓虹/逆光]，情绪：[情绪词]。\n细节要求：[肤质/材质/颗粒感]。\n输出：高写实摄影风格图像。',
    tags: ['摄影', '写实', '镜头', '时尚', '商业'],
    guidance: ['指定机位、镜头、光源、质感、背景和动作。', '加入可信的小瑕疵增强纪实感。'],
    pitfalls: ['商业美妆之外，避免过度磨皮。', '需要时加入手部、文字、结构类负面约束。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-photo',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-street-accident-moment',
    previewImage: 'inspiration/case376.webp',
    previewSourceLabel: '@Shinning1010',
    previewSourceUrl: 'https://x.com/Shinning1010/status/2050693240253214894',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-376',
    title: '街头意外瞬间摄影',
    category: '摄影与写实',
    sourceCategory: 'Photography & Realism',
    description: '生成手机纪实风街头瞬间，并加入负面约束。',
    prompt: '生成一张竖版手机纪实照片，主题是[意外事件/日常瞬间]发生在[街头/室外地点]。\n主体：[物品/人物动作/现场痕迹]，必须呈现真实的材质状态，例如[液体扩散/冰块散落/纸张褶皱/灰尘颗粒]。\n环境：[地面材质/墙面/街景元素]，保留自然杂乱和生活痕迹。\n光线：[正午强光/阴天散射光/夜间路灯]，阴影要符合真实方向，可加入[人物影子/路牌影子/树影]。\n镜头：手持手机视角，略微俯拍或低角度，构图自然，像随手拍到的现场。\n画面质感：raw unedited photo look，自然色彩，真实纹理，高细节。\n负面约束：不要插画、动漫、CGI、棚拍光、过度干净、过度构图、假液体、漂浮物、品牌文字、水印、海报设计感。\n输出：一张可信的日常纪实摄影图。',
    tags: ['摄影', '写实', '场景', '旅行', '社媒'],
    guidance: ['描述具体瞬间、机位高度、运动模糊和街景。', '加入避免摆拍和广告棚拍感的限制。'],
    pitfalls: ['避免画面过于干净。', '让事件看起来可信。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-photo',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-illustration-art-style',
    previewImage: 'inspiration/case346.webp',
    previewSourceLabel: '@dotey',
    previewSourceUrl: 'https://x.com/dotey/status/2048529821706195442',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-346',
    title: '插画与艺术风格',
    category: '插画与艺术',
    sourceCategory: 'Illustration & Art',
    description: '生成动漫、水彩、水墨、材质实验和艺术风格图。',
    prompt: '创作[题材]插画，主角为[角色/主体]。\n画风：[日漫/水彩/扁平/厚涂]，线条：[细腻/粗犷]。\n配色：[配色方案]，背景：[简洁/复杂场景]。\n构图：[近景/中景/远景]，重点表现[细节]。\n输出：可用于封面或社媒发布的高质量插画。',
    tags: ['插画', '艺术', '风格', '叙事', '创意'],
    guidance: ['定义构图、主体、配色、笔触材质、情绪和完成度。', '参考图任务需要说明保留哪些特征。'],
    pitfalls: ['避免只写风格，不写构图。', '使用参考图时锁定角色识别。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-illustration',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-character-design-sheet',
    previewImage: 'inspiration/case347.webp',
    previewSourceLabel: '@oggii_0',
    previewSourceUrl: 'https://x.com/oggii_0/status/2048614158699217302',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-347',
    title: '角色设定表',
    category: '人物与角色',
    sourceCategory: 'Characters & People',
    description: '生成角色设定、动作分解和一致性参考。',
    prompt: '设计[角色身份]角色设定图。\n外观：[年龄/发型/服饰/配件]，性格：[关键词]。\n姿态：[站姿/动态动作]，表情：[情绪]。\n世界观：[时代/阵营/职业]，标志性元素：[元素]。\n输出：角色主视图 + 风格统一的人设图。',
    tags: ['角色', '动作', '风格', '插画', '叙事'],
    guidance: ['定义身份锚点、服装、比例、动作数量和版式。', '保持脸、发型和服装细节一致。'],
    pitfalls: ['避免不同动作里服装细节变化。', '画面拥挤时减少动作数量。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-character',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-3d-collectible-toy',
    previewImage: 'inspiration/case378.webp',
    previewSourceLabel: '@Genematicai',
    previewSourceUrl: 'https://x.com/Genematicai/status/2050654848216109429',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-378',
    title: '3D 收藏玩具',
    category: '人物与角色',
    sourceCategory: 'Characters & People',
    description: '把参考图转换成高级 3D 收藏玩具效果。',
    prompt: '将输入照片转换为高端 3D 收藏玩具形象。\n身份保持：保留原始人物/角色的脸部身份、主要发型、表情气质和服装识别点。\n造型比例：大头设计，五官轻微夸张，身体比例玩具化，但整体仍保持高级设计感。\n材质：哑光 vinyl / resin / collectible figure finish，皮肤和服饰材质要有细节。\n灯光与背景：柔和棚拍光，干净背景，[黑色/白色/品牌色]，主体居中，轮廓清晰。\n质感：超清锐度，真实材质反射，8K render，premium designer toy aesthetic。\n约束：不要改变身份，不要廉价塑料感，不要多角色，不要复杂背景，不要文字水印。\n输出：一张完整的高端收藏玩具渲染图。',
    tags: ['角色', '3D', '风格', '商业', '创意'],
    guidance: ['保留参考图中的脸和服装锚点。', '指定材质、包装、底座、光线和收藏比例。'],
    pitfalls: ['避免没有身份细节的通用玩具。', '包装文字保持少量且准确。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-character',
    referenceCount: 1,
  },
  {
    id: 'canghe-template-scene-storytelling',
    previewImage: 'inspiration/case204.webp',
    previewSourceLabel: '@joshesye',
    previewSourceUrl: 'https://x.com/joshesye/status/2046596222505361866',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-204',
    title: '场景叙事',
    category: '场景与叙事',
    sourceCategory: 'Scenes & Storytelling',
    description: '生成分镜、世界观、故事场景和情绪节奏。',
    prompt: '生成[故事主题]场景图，发生在[时间+地点]。\n主事件：[事件描述]，主角：[角色]，冲突点：[冲突]。\n镜头语言：[广角建立镜头/中景叙事/特写]。\n氛围：[紧张/温暖/悬疑]，色调：[冷/暖/高反差]。\n输出：具备叙事张力的场景概念图。',
    tags: ['场景', '叙事', '分镜', '插画', '社媒'],
    guidance: ['定义人物、地点、时间、冲突、情绪和机位。', '让场景细节服务故事。'],
    pitfalls: ['避免通用幻想背景。', '让故事线索在画面里可见。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-scene',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-history-classical-themes',
    previewImage: 'inspiration/case375.webp',
    previewSourceLabel: '@ToroJushiAi',
    previewSourceUrl: 'https://x.com/ToroJushiAi/status/2050713034503409874',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-375',
    title: '历史与古风题材',
    category: '历史与古风题材',
    sourceCategory: 'History & Classical Themes',
    description: '生成朝代服饰、长卷叙事、诗词和传统题材。',
    prompt: '生成[朝代/古风设定]题材画面，主题为[主题]。\n人物：[身份/服饰/器物]，场景：[宫廷/市井/山水]。\n美术风格：[工笔/写意/影视写实]，色调：[色调]。\n文化细节：[纹样/礼制/建筑要素]。\n输出：历史氛围准确的古风题材图。',
    tags: ['历史', '古典', '长卷', '插画', '叙事'],
    guidance: ['指定朝代、服饰制度、器物参考、版式和文化气质。', '明确长卷、册页或海报形式。'],
    pitfalls: ['需要历史准确时，避免朝代混搭。', '约束随机现代物件。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-history',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-document-publishing',
    previewImage: 'inspiration/case222.webp',
    previewSourceLabel: '@MrLarus',
    previewSourceUrl: 'https://x.com/MrLarus/status/2046231542817497392',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-222',
    title: '文档与出版物',
    category: '文档与出版物',
    sourceCategory: 'Documents & Publishing',
    description: '生成白皮书、手册、百科图鉴和页面系统。',
    prompt: '制作[文档类型，如菜单/杂志内页/报纸版式]。\n版面结构：[栏数/页边距/标题层级]。\n内容模块：[封面区/正文区/图表区/脚注]。\n字体风格：[衬线/无衬线]，配色：[配色方案]。\n输出：可读性强、版式规范的出版物视觉稿。',
    tags: ['文档', '出版', '版式', '信息图', '教育', '科技'],
    guidance: ['定义页面尺寸、分栏、目录、图表系统和字体层级。', '使用可读标题、表格、标签和页面节奏。'],
    pitfalls: ['避免密集小字。', '让图表和说明对齐页面网格。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-document',
    referenceCount: 0,
  },
  {
    id: 'canghe-template-concept-product-breakdown',
    previewImage: 'inspiration/case370.webp',
    previewSourceLabel: '@ShamsAmin56',
    previewSourceUrl: 'https://x.com/ShamsAmin56/status/2050281206139461780',
    exampleUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/gallery-part-2.md#case-370',
    title: '概念产品研发拆解',
    category: '其他应用场景',
    sourceCategory: 'Other Use Cases',
    description: '生成研发板、拆解图、混合任务和特殊输出。',
    prompt: '为[产品/家具/装置]生成一张完整的概念产品研发拆解板，而不是单张成品渲染图。\n\n核心概念：\n把[灵感来源，如揉皱纸团/贝壳/折纸/机械结构]转译成[产品类型]。\n设计哲学：[一句话说明功能与情绪，例如“把受控混乱转化为高舒适度座椅”]。\n\n画面结构：\n中心：高质量 hero render，展示最终产品的主要形态、材质和比例。\n左侧：观察与形态分析，包含灵感图、轮廓提取、结构线、折痕/纹理/受力方向标注。\n中部：形态迭代过程，展示从原始形态到产品外壳的 3-5 个演化步骤。\n下方：人体工学或使用场景验证，包含尺寸、角度、使用姿态和关键功能说明。\n右侧：结构集成与材料方案，展示内部骨架、外壳、软垫/面料/连接件等分层拆解。\n底部：最终材质、表面纹理、颜色方案和关键规格表。\n\n视觉风格：\n工业设计提案板，干净白底或浅灰背景，技术图纸 + 产品摄影混合风格，细线标注，清晰标题，真实阴影，材质细节可见。\n\n约束：\n不要只画一个漂亮产品；必须展示分析、迭代、人体工学、结构、材料和规格。\n不要让文字挤满画面；每个阶段只保留短标题和关键标签。\n产品外形应保留[灵感来源]的识别特征，但必须看起来可制造、可使用。',
    tags: ['创意', '研发', '特殊输出', '其他应用场景', '商品', '科技'],
    guidance: ['定义产物类型、组件、标签、材质逻辑和展示格式。', '使用清晰标注和受控技术风格。'],
    pitfalls: ['避免任务边界过泛。', '标签要短，组件关系要清楚。'],
    sourceUrl: 'https://github.com/freestylefly/awesome-gpt-image-2/blob/65a9c57a1968a13f2f1997c58409cac9aa146bc7/docs/templates.md#tpl-other',
    referenceCount: 0,
  },
]
